# Generated by Django 5.1.1 on 2024-09-11 03:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=10)),
                ('nro_documento', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, max_length=255, null=True)),
                ('user_telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('puntaje_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_viandas_ultimo_mes', models.IntegerField()),
            ],
            options={
                'db_table': 'colaborador_reconocido',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rubro', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, max_length=255, null=True)),
                ('user_telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'solicitante',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_min_puntos', models.IntegerField()),
                ('cant_min_viandas_ultimo_mes', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cant_max_colaboradores', models.IntegerField()),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendar_colaboradores_app.solicitante')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recomendacion', models.DateField(default=datetime.date.today)),
                ('colaboradores', models.ManyToManyField(to='recomendar_colaboradores_app.colaborador')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendar_colaboradores_app.solicitud')),
            ],
            options={
                'db_table': 'recomendacion',
            },
        ),
    ]
