@startuml diagramaDeClases

class PersonaHumana {
 - tipoDocumento: String
 - nroDocumento: String
 - contacto: Contacto
 - direccion: String
 - nombre: String
 - apellido: String
 - fechaNacimiento: LocalDate
 - puntajeNeto: float
 - cantidadViandasUltimoMes: Integer
}

class Contacto {
 - telefono: String
 - celular: String
 - mail: String
 - userIDTelegram: String
}

PersonaHumana --> Contacto

class Recomendador{
    + filtrarReconocidos() : List<PersonaHumana>
}

class Solicitud {
    - cantMinPuntos: Integer
    - cantMinViandasUltimoMes: Integer
    - fecha: LocalDate
    - cantMaxColaboradores: Integer
    - solicitante: Solicitante 
}

class Solicitante {
 - razonSocial: String
 - rubro: String
 - whatsapp: String
 - mail: String
 - userTelegram: String
 - direccion: String
}

Solicitud --> Solicitante

'-----------------------------------------------------------------------'

entity colaborador_reconocido {
 * id: INTEGER(11) <<PK>>
 --
 * tipoDocumento: VARCHAR(10)
 * nroDocumento: CHAR(8)
 whatsapp: VARCHAR(255)
 mail: VARCHAR(255)
 userTelegram: VARCHAR(255)
 * direccion: VARCHAR(255)
 * nombre: VARCHAR(255)
 * apellido: VARCHAR(255)
 * fechaNacimiento: LocalDate
 * puntajeNeto: DECIMAL
 * cantidadViandasUltimoMes: NUMBER
}

entity solicitud {
 * id: INTEGER(11) <<PK>>
 --
 * cantMaxColaboradores: NUMBER
 * cantMinPuntos: NUMBER
 * cantMinViandasUltimoMes: NUMBER
 * solicitante: ¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿🥸????????????????????
 * fecha: DATE
}

entity solicitante {
 * id: INTEGER(11) <<PK>>
 --
 * id_usuario: INTEGER(11) <<FK>>
 * id_rubro: INTEGER(11) <<FK>>
 whatsapp: VARCHAR(255)
 mail: VARCHAR(255)
 userTelegram: VARCHAR(255)
 * direccion: VARCHAR(255)
}

solicitud   ||--o{colaborador_reconocido
solicitante ||--o{ solicitud

@enduml